# Generated by Django 3.1.5 on 2021-01-20 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture_Count', models.CharField(max_length=200)),
                ('CR', models.CharField(max_length=200)),
                ('Year', models.IntegerField(default=0)),
                ('Make', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Style', models.CharField(max_length=200)),
                ('Odometer', models.IntegerField(default=0)),
                ('Color', models.CharField(max_length=200)),
                ('Stock', models.CharField(max_length=200)),
                ('Grade', models.CharField(max_length=200)),
                ('Sale_Date', models.CharField(max_length=200)),
                ('Lane', models.CharField(max_length=200)),
                ('Run_number', models.CharField(max_length=200)),
                ('Price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture_Count', models.CharField(max_length=200)),
                ('CR', models.CharField(max_length=200)),
                ('Year', models.IntegerField(default=0)),
                ('Make', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Style', models.CharField(max_length=200)),
                ('Odometer', models.IntegerField(default=0)),
                ('Color', models.CharField(max_length=200)),
                ('Stock', models.IntegerField(default=0)),
                ('Grade', models.CharField(max_length=200)),
                ('Sale_Date', models.CharField(max_length=200)),
                ('Run_number', models.CharField(max_length=200)),
                ('Lane', models.CharField(max_length=200)),
                ('Lot', models.CharField(max_length=200)),
                ('VIN', models.CharField(max_length=200)),
                ('Day', models.DateField(default=datetime.date(2021, 1, 20))),
            ],
            options={
                'ordering': ('Model',),
            },
        ),
    ]
