# Generated by Django 3.1.4 on 2020-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsale',
            name='Predicted_Price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postsale',
            name='Sale_Date',
            field=models.CharField(max_length=200),
        ),
    ]
