# Generated by Django 3.1.4 on 2020-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0002_auto_20201229_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture_Count', models.CharField(max_length=200)),
                ('CR', models.CharField(max_length=200)),
                ('Year', models.IntegerField(default=0)),
                ('Make', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Style', models.CharField(max_length=200)),
                ('Odometer', models.IntegerField(default=0)),
                ('Color', models.CharField(max_length=200)),
                ('Stock', models.IntegerField(default=0)),
                ('Grade', models.CharField(max_length=200)),
                ('Sale_Date', models.CharField(max_length=200)),
                ('Run_number', models.CharField(max_length=200)),
                ('Lane', models.CharField(max_length=200)),
                ('Lot', models.CharField(max_length=200)),
                ('VIN', models.CharField(max_length=200)),
                ('Predicted_Price', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postsale',
            name='Lot',
        ),
        migrations.RemoveField(
            model_name='postsale',
            name='Predicted_Price',
        ),
        migrations.RemoveField(
            model_name='postsale',
            name='VIN',
        ),
        migrations.AddField(
            model_name='postsale',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
