# Generated by Django 3.1.4 on 2020-12-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0003_auto_20201231_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsale',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
