# Generated by Django 3.1.4 on 2020-12-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0004_auto_20201231_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postsale',
            new_name='Postsales',
        ),
    ]
