# Generated by Django 3.1.4 on 2020-12-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0005_auto_20201231_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsales',
            name='Stock',
            field=models.CharField(max_length=200),
        ),
    ]
