# Generated by Django 3.1.4 on 2021-01-06 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0007_auto_20210104_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='Day',
            field=models.DateField(default=datetime.date(2021, 1, 6)),
        ),
    ]
