# Generated by Django 3.1.5 on 2021-01-08 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carguys', '0008_presale_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presale',
            name='Day',
            field=models.DateField(default=datetime.date(2021, 1, 8)),
        ),
    ]
